# Generated by Django 4.2.16 on 2024-11-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('imgUrl', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=10)),
                ('singerId', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
