# Generated by Django 4.2.16 on 2024-11-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
