# Generated by Django 4.2.16 on 2024-11-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgUrl', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('songCount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
